{% set name = "raypier" %}
{% set version = "0.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/raypier-{{ version }}.tar.gz
  sha256: e7813e835f29cc4ffab4332785e1ccb49148c7433895a0fbd0f15dcaf2b4eb7a

build:
  number: 0
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  

requirements:
  host:
    - cython >=0.29
    - numpy ==1.19
    - pip
    - python >=3.7
    - vtk >=9.0
    - traits >=6.0
    - mayavi >=4.7
    - traitsui >=7.0
    - configobj >=5.0
  run:
    - python >=3.7
    - vtk >=9.0
    - traits >=6.0
    - mayavi >=4.7
    - traitsui >=7.0
    - configobj >=5.0

test:
  imports:
    - raypier
    - raypier.core.ctracer
    - raypier.core.cmaterials
    - raypier.core.cdistortions
    - raypier.core.cshapes
    - raypier.core.cfields
    - raypier.core.cfaces
  commands:
    - pip check
  requires:
    - pip
    - configobj
    - numpy ==1.19

about:
  home: https://groups.google.com/u/1/g/python-raytrace
  summary: A optical ray-tracing package, for design, optimisation and visualisation of mirror/lens systems.
  dev_url: https://github.com/bryancole/raypier_optics.git
  license: GPL3
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - 230838
