{% set name = "raypier" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/raypier-{{ version }}.tar.gz
  sha256: 5ed1b473e26200c8e8a99ec5e969e914963a974a47812c47626748c48071c167

build:
  number: 0

requirements:
  build:
    - cython >=0.29
  host:
    - cython >=0.29
    - numpy ==1.19
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - vtk >=9.0
    - traits >=6.0
    - mayavi >=4.7
    - traitsui >=7.0

test:
  imports:
    - raypier
    - raypier.core.ctracer
    - raypier.core.cmaterials
    - raypier.core.cdistortions
    - raypier.core.cshapes
    - raypier.core.cfields
    - raypier.core.cfaces
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://groups.google.com/u/1/g/python-raytrace
  summary: A optical ray-tracing package, for design, optimisation and visualisation of mirror/lens systems.
  dev_url: https://github.com/bryancole/raypier_optics.git
  license: GPL3
  license_file: COPYRIGHT

extra:
  recipe-maintainers:
    - 230838
